### ISSUE TITLE
add more options and visibility 

### ISSUE THREAD

**Issue by sliddjur** [munim/ulauncher-ip-lookup#1]
hello, can you add option to show asn information and threath information aswell?

**Comment by munim** [comment]
@sliddjur Thanks for brining this up. I think this is a great request. ipdata.co also provide necessary information on ASN and threats. I need to have a look how I can fit it in the ulauncher result list. I am open to any suggestions.

**Comment by sliddjur** [comment]
I forked your project and added the info I want to see. 
https://github.com/sliddjur/ulauncher-ip-lookup/commit/196fc4da62e7e62cc1416fea3d17126b5c7458df
